// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleBlog.Data;

#nullable disable

namespace SimpleBlog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240911120902_initalDataBlog")]
    partial class initalDataBlog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleBlog.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Abdullah Ali",
                            Content = "I Love Asp.Net",
                            CreatedDate = new DateTime(2024, 9, 11, 15, 9, 1, 146, DateTimeKind.Local).AddTicks(218),
                            Title = "ASP.Net"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Malak Mohamed",
                            Content = "I Love API Core",
                            CreatedDate = new DateTime(2024, 9, 11, 15, 9, 1, 146, DateTimeKind.Local).AddTicks(278),
                            Title = "API Core"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Omar Ali",
                            Content = "I Love MVC Core",
                            CreatedDate = new DateTime(2024, 9, 11, 15, 9, 1, 146, DateTimeKind.Local).AddTicks(286),
                            Title = "MVC Core"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
